# https://github.com/GoogleContainerTools/skaffold/tree/master/examples
# https://github.com/GoogleContainerTools/skaffold/blob/master/examples/buildpacks-java/skaffold.yaml

apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: spring-boot-demo
      buildpacks:
        # renovate: datasource=docker depName=paketobuildpacks/builder-jammy-base
        builder: "paketobuildpacks/builder-jammy-base:0.4.609"
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
