spring:
  jmx:
    enabled: false

server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: "/"

management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  server:
    port: 8080
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/actuator"
      exposure:
        include: "health,info,metrics,prometheus,loggers,env,configprops"
  endpoint:
    env:
      enabled: true
    configprops:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true
    sessions:
      enabled: true

info:
  build:
    artifact: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

hotel:
  service:
    name: 'default profile'

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.test.example: DEBUG
  file:
    path: "."
    name: "application.log"
  pattern:
    console: "%clr(%d{YYYY-MM-dd E HH:mm:ss.SSS}){faint} %clr(%-5p) %clr(${PID}){faint} %clr([%8.15t]){faint} %clr(%c{1}:%L){cyan} %clr(:){red} %clr(%m){faint}%n"
    file: "%d{YYYY-MM-dd E HH:mm:ss.SSS} %-5p ${PID} [%8.15t] %c{1}:%L : %m%n"

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
