spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: "/"

#management endpoints on a separate port
management:
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  server:
    port: 8080

  endpoints:
    enabled-by-default: false
    web:
      base-path: "/actuator"
      exposure:
        include: "health,info,metrics,prometheus,loggers,env,configprops"
  endpoint:
    env:
      enabled: true
    configprops:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true
    sessions:
      enabled: true

# project info followed by actual injected pom-specified values.
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: "@project.description@"
    version: @project.version@

hotel.service:
  name: 'default profile'

logging.pattern.console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
logging.level.ROOT: "INFO"
logging.level.org.springframework.: "INFO"
logging.level.com.test.example: "DEBUG"
logging.file.path: "/var/log"
logging.file.name: "application.log"
logging.pattern.file: "%d{yyyy-MM-dd } [%thread] %-5level %logger{36} - %msg%n"

#cors.allowed-origins[0]: "*"
#info.actuator: "http://localhost:8080/actuator"
#info.swagger: "http://localhost:8080/v2/api-docs"

#---
#spring:
#  profiles: test
#  h2:
#    console:
#      enabled: true
#
#spring.jpa:
#    hibernate.ddl-auto: create-drop
#
#hotel.service:
#  name: 'test profile:'
#
#logging:
#  file: boot_example.log
#  org.hibernate: INFO
