version: '3'

services:
  database:
    image: 'docker.io/mongo:4.2.3'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=mongo-admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo-admin-password
    ports:
      - "27017-27019:27017-27019"
    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ~/.mongodb_data:/data/db

#volumes:
#  mongodb_data:
#    driver: local
